before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    dir: cmd

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

release:
  mode: keep-existing

brews:
  - name: newrelic-integration-e2e
    tap:
      owner: newrelic-forks
      name: newrelic-integration-e2e-action
      token: "{{ .Env.GITHUB_TOKEN }}"
    folder: Formula
    description: "Allows New Relic developers to run e2e on OHIs"
