name: newrelic-integration-e2e-action
description: Run e2e tests for the newrelic integrations.
inputs:
  spec_path:
    description: Path to the test specification file.
    required: true
  account_id:
    description: New Relic account id used to test the integration
    required: true
  license_key:
    description: New Relic license key used to test the integration
    required: true
  api_key:
    description: New Relic api key used to test the integration
    required: true
  retry_seconds:
    description: Number of seconds to wait after retrying a test
    required: false
    default: "30"
  retry_attempts:
    description: Number of attempts a failed test can be retried
    required: false
    default: "10"
  agent_dir:
    description: Custom agent dir
    required: false
  agent_enabled:
    description: Enable the agent execution
    required: false
    default: "true"
  verbose:
    description: Verbose mode enabled
    required: false
    default: "true"
  region:
    description: The region where to send/read the e2e data
    required: false
    default: "US"

runs:
  using: "composite"
  steps:
    - id: run-spec
      run: make -C ${{ github.action_path }} COMMIT_SHA=${{ github.sha }} AGENT_ENABLED=${{ inputs.agent_enabled }} ROOT_DIR=${{ github.workspace }} AGENT_DIR=${{ inputs.agent_dir }} ACCOUNT_ID=${{ inputs.account_id }} API_KEY=${{ inputs.api_key }} LICENSE_KEY=${{ inputs.license_key }} SPEC_PATH=${{ inputs.spec_path }} RETRY_ATTEMPTS=${{ inputs.retry_attempts }} RETRY_SECONDS=${{ inputs.retry_seconds }} VERBOSE=${{ inputs.verbose }} REGION=${{ inputs.region }} run
      shell: bash
