name: newrelic-integration-e2e-action
description: Run e2e tests for the newrelic integrations.
inputs:
  spec_path:
    description: Path to the test specification file.
    required: true
  account_id:
    description: New Relic account id used to test the integration
    required: true
  license_key:
    description: New Relic license key used to test the integration
    required: true
  api_key:
    description: New Relic api key used to test the integration
    required: true
  retry_seconds:
    description: Number of seconds to wait after retrying a test
    required: false
    default: "60"
  retry_attempts:
    description: Number of attempts a failed test can be retried
    required: false
    default: "15"
  agent_enabled:
    description: Enable the agent execution
    required: false
    default: "true"
  verbose:
    description: Verbose mode enabled
    required: false
    default: "true"
  region:
    description: |
      The region where to send/read the e2e data. The possible values are:
       * "US" for New Relic's US-based production,
       * "EU" for New Relic's EU-based production,
       * "Staging" for New Relic's staging (internal use only) and
       * "Local" for a local development of the backend (internal use only).

      The values at the time of writing this are from this commit: https://github.com/newrelic/newrelic-client-go/blob/ece2430d7cfd7f5bd69c300568a7e9ec24f287ca/pkg/region/region_constants.go#L7-L20
    required: false
    default: "US"
  scenario_tag:
    description: Allow customers to set the testing cluster name as their cluster name if they do not want to use the auto-generated random cluster name.
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - id: run-spec
      run: make -C ${{ github.action_path }} COMMIT_SHA=${{ github.sha }} AGENT_ENABLED=${{ inputs.agent_enabled }} ROOT_DIR=${{ github.workspace }} ACCOUNT_ID=${{ inputs.account_id }} API_KEY=${{ inputs.api_key }} LICENSE_KEY=${{ inputs.license_key }} SPEC_PATH=${{ inputs.spec_path }} RETRY_ATTEMPTS=${{ inputs.retry_attempts }} RETRY_SECONDS=${{ inputs.retry_seconds }} VERBOSE=${{ inputs.verbose }} REGION=${{ inputs.region }} SCENARIO_TAG=${{ inputs.scenario_tag }} run
      shell: bash
