name: newrelic-integration-e2e-action
description: Run e2e tests for the newrelic integrations.
inputs:
  spec_path:
    description: Path to the test specification file.
    required: true
  account_id:
    description: New Relic account id used to test the integration
    required: true
  license_key:
    description: New Relic license key used to test the integration
    required: true
  api_key:
    description: New Relic api key used to test the integration
    required: true
  retry_seconds:
    description: Number of seconds to wait after retrying a test
    required: false
    default: "30"
  retry_attempts:
    description: Number of attempts a failed test can be retried
    required: false
    default: "10"
  agent_enabled:
    description: Enable the agent execution
    required: false
    default: "true"
  verbose:
    description: Verbose mode enabled
    required: false
    default: "true"
  region:
    description: |
      The region where to send/read the e2e data. The possible values are:
       * "US" for New Relic's US-based production,
       * "EU" for New Relic's EU-based production,
       * "Staging" for New Relic's staging (internal use only) and
       * "Local" for a local development of the backend (internal use only).

      The values at the time of writing this are from this commit: https://github.com/newrelic/newrelic-client-go/blob/ece2430d7cfd7f5bd69c300568a7e9ec24f287ca/pkg/region/region_constants.go#L7-L20
    required: false
    default: "US"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: '${{ github.action_path }}/go.mod'

    - name: Run external Job
      shell: bash
      run: |
        cd "${{ github.action_path }}" && go build -o newrelic-integration-e2e ./cmd && \
        ./newrelic-integration-e2e \
          --commit_sha="${{ inputs.commit_sha }}" \
          --retry_attempts="${{ inputs.retry_attempts }}" \
          --retry_seconds="${{ inputs.retry_seconds }}" \
          --account_id="${{ inputs.account_id }}" \
          --api_key="${{ inputs.api_key }}" \
          --license_key="${{ inputs.license_key }}" \
          --spec_path="${{ inputs.spec_path }}" \
          --verbose_mode="${{ inputs.verbose_mode }}" \
          --agent_enabled="${{ inputs.agent_enabled }}" \
          --region="${{ inputs.region }}"
